# Generated by Django 3.1.6 on 2021-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_jobapplication_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='contact_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='was_referred',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
